### PR TITLE
fix-patch for pub/sub service | ready for test

### PR DESCRIPTION
**Pull request by fuzsh**
poof ....
💩

### CODE REVIEW

**Comment by fuzsh** [comment]
@yeganeh666 Since you are the developer of this library and you are writing a complete service, it is better to apply items such as those in the above changes to other sections.

I think this service can be a very complete and comprehensive service in all respects for all developers, thank you for building something as well.

**Comment by yeganeh666** [comment]
thanks for amazing fix =))))

**Comment by yeganeh666** [comment]
@yeganeh666 در سطح جهانی داشتم آبروداری میکردما وگرنه تو دلم کلی فحشه

**Comment by yeganeh666** [comment]
@yeganeh666 =||||||||||||||||||||||||||||||||||||||||||||

**Comment by fuzsh** [comment]
@yeganeh666 Thank you very much for reviewing this pull Request and I was very happy when you checked it out.
👽گ👽

**Pull request merged**
